version: 2

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org,direct
before:
  hooks:
    - go mod download
builds:
- id: cert-checker
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
  main: ./cmd/main.go
  binary: cert-checker

dockers_v2:
  - id: cert-checker-image
    dockerfile: Dockerfile.goreleaser
    ids:
      - cert-checker
    images:
      - mogensen/cert-checker
    tags:
      - latest
      - v{{ .Version }}
    platforms:
      - linux/amd64
      - linux/arm64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy

archives:
  - name_template: >-
      cert-checker_{{ title .Os }}_{{ if eq .Arch "386" }}i386{{ else if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
