# Build stage
FROM golang:1.26-alpine AS build-env

# Build runtime container
FROM scratch
ARG TARGETPLATFORM
WORKDIR /app

COPY --from=build-env /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --chown=35212:35212 $TARGETPLATFORM/cert-checker /app/cert-checker

USER 35212:35212

ENTRYPOINT ["/app/cert-checker"]
