name: Test coverage

on:
  push: {}

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Generate coverage report
      run: go test ./... -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage report
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.txt
        flags: unittests
