name: Release with goreleaser

on:
  push:
    tags:
    - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Set up QEMU for multi-platform builds
      uses: docker/setup-qemu-action@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Download dependencies
      run: go mod download

    - name: Release via goreleaser
      uses: goreleaser/goreleaser-action@v7
      with:
        version: "~> v2"
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
